[workspace]
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "molecularGSM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.0.2,<5"
cxx-compiler = ">=1.9.0,<2"
make = ">=4.4.1,<5"
rattler-build = ">=0.41.0,<0.42"
c-compiler = ">=1.9.0,<2"
libgcc = ">=15.1.0,<16"
libstdcxx-ng = ">=15.1.0,<16"
blas = ">=2.131,<3"
mkl = ">=2024.2.2,<2025"
mkl-devel = ">=2024.2.2,<2025"
mkl-static = ">=2024.2.2,<2025"
mkl-include = ">=2024.2.2,<2025"
mopac = ">=23.1.2,<24"
